scan_timeout = 100
add_newline = false
format ="""
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$conda\
$python\
$line_break\
$character"""

[directory]
style = "blue"

[directory.substitutions]
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"
"Music" = " Music"
"Pictures" = " Pictures"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[(virtualenv:$virtualenv)]($style) "
style = "dimmed green"

[conda]
format = '[(conda:$environment)]($style) '
style = "dimmed green"
ignore_base = true
