add_newline = false

format ="""$directory\
$git_branch\
$git_status\
$character
"""

[directory.substitutions]
"Documents" = "󰈙 Documents "
"Downloads" = "  Downloads "
"Music" = "  Music "
"Pictures" = "  Pictures "
